config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :services, only: %i[index show] do
    resources :bookings, only: %i[new create show]
    resources :reviews, only: %i[new create show]
  end
  get "team", to: "pages#team"

  get "contact", to: "pages#contact"

  resources :bookings, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :user
  validates :start_date, :end_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
  validates :rating, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_title_and_address,
    against: [:name, :title, :address],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :services, through: :bookings
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
skip_before_action :authenticate_user!, only: :new
  def new
    @booking = Booking.new
    @service = Service.find(params[:service_id])
  end

 def create
    @service = Service.find(params[:service_id])
    @booking = Booking.new(booking_params)
    @booking.service = @service
    @booking.user = current_user

    if @booking.save
      redirect_to service_path(@service), alert: "Booking Confirmed!"

    else
      render :new
    end
end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to service_path(@booking.list)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date,:end_date)

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @services = Service.all.sample(3)
  end

  def contact
  end
  
  def team
    
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 def new
    @review = Review.new
    @service = Service.find(params[:service_id])
  end

  def create
    @service = Service.find(params[:service_id])
    @review = Review.new(review_params)
    @review.service = @service
    @review.user = current_user
    if @review.save
      redirect_to service_path(@service)
    else
      render :new
    end
  end


  private


  def review_params
    params.require(:review).permit(:comment, :rating)
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      @services = Service.search_by_name_and_title_and_address(params[:query])
    else
      @services = Service.all
    end
    @markers = @services.geocoded.map do |service|
      {
        lat: service.latitude,
        lng: service.longitude,
        info_window: render_to_string(partial: "info_window", locals: { service: service })
        # image_url: helpers.asset_url('logo.png')
      }
    end
  end

  def show
    @service = Service.find(params[:id])
    @markers = [
      {
        lat: @service.latitude,
        lng: @service.longitude,
        info_window: render_to_string(partial: "info_window", locals: { service: @service }),
        # image_url: helpers.asset_url('logo.png')
      }
    ]
  end


  private

  def services_params
    params.require(:service).permit(:name, :title, :address, :price, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">

<h4>Choose a booking <%= @service.title %></h4>
        <%= simple_form_for [@service,@booking] do |f| %>
          <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BEAUTYFirst</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body style ="background-color: white">
   <div class="page-container">
  <%= render "shared/navbar" %>

  <main id="main-content">
    <%= yield %>
  </main>
  </div>
  <%= render "shared/footer" %>

</body>

</html>

app/views/pages/home.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h3> Welcome to your first beauty App!</h3>
    <p>Checkout all our services</p>
    <button class="btn btn-primary"><%= link_to "discover", services_path  %></button>
  </div>
 </div>

 <div class="service-text"><h2 id="banner-typed-text" style= "text-align:center;min-height: 25px;"></h2></div>

 <div class="search-form-control">
 <%= form_tag services_path, method: :get do %><%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a service"%><%= submit_tag "Search", class: "btn-search btn-primary" %><% end %>
</div>



<div class= "cards-container">
    <% @services.sample(3).each do |service| %>
      <div class="card-trip">
        <%= cl_image_tag service.photo.key %>
        <div class="card-trip-infos">
          <div>
            <h2><%= service.title %></h2>
            <p>find the best <%= service.title %> in town</p>
          </div>
          <div>
            <%= link_to service_path(service), class: 'text-decoration-none' do %>
            <div class="btn btn-primary">Book now</div>
            <% end %>
            <h2 class="card-trip-pricing"><%= service.price %> Euros</h2>
          </div>
        </div>
      </div>
    <% end %>
</div>


<div class="container mx-0 ">
    <h2 class="text-centered">How does it work?</h2>
    <div class="cards-1 d-flex">

      <div class="card-1 col-sm-4  shadow-sm p-3 mb-5 bg-white rounded mx-3 ">
       <%= image_tag "works.png", class: "work w-50 p-3" %>
        <h4 style="color: #B7B7A4 "> Find the best beauty service </h4>
        <p style="color: #cb997e">Locate the best beauty service near you with our dynamic map! </p>
      </div>

      <div class="card-1 col-sm-4 shadow-sm p-3 mb-5 bg-white rounded mx-3">
       <%= image_tag "works.png", class: "work w-50 p-3" %>
        <h4 style="color: #B7B7A4 ">Book through our website </h4>
        <p style="color: #cb997e">Book your appointment, connect directly with your calendar.</p>
      </div>

      <div class="card-1 col-sm-4  shadow-sm p-3 mb-5 bg-white rounded mx-3">
         <%= image_tag "works.png", class: "work w-50 p-3 " %>
        <h4 style="color: #B7B7A4 ">Pay online and give feedback</h4>
        <p style="color: #cb997e">Finally give your feedback to your service, and book again on our website!</p>
      </div>

    </div>
  </div>

app/views/pages/team.html.erb
<div class= banner>
  <h1>OUR TEAM</h1>
</div>

<div class= "team-container">
    <div class="text-center">
    <%= image_tag "mayen.jpg", class: "avatar-large may", alt: "avatar-large" %>
    <h2>Mayen</h2>
    </div>
    <div class="text-center">
    <%= image_tag "belle gosse.JPG", class: "avatar-large jo", alt: "avatar-large" %>
  <h2>Johann</h2>
    </div>
    <div class="text-center">
    <%= image_tag "relou.jpg", class: "avatar-large trist", alt: "avatar-large" %>
     <h2>Tristan</h2>
    </div>
</div>

app/views/reviews/new.html.erb
  <p class="t"> Add a review on your service <%= @service.title %></p>
   <%= simple_form_for [@service,@review] do |f| %>
    <%= f.input :comment %>
    <div class="rating-container">
      <%= f.input :rating, collection: [['⭐️',1], ['⭐️',2],['⭐️',3], ['⭐️',4],['⭐️',5]], as: :radio_buttons, label: "Rate your experience" %>

<!--       <input type="radio" name="review[rating]" value="5" id="star-5"> <label for="star-5"><i class="fas fa-star"></i></label>
      <input type="radio" name="review[rating]" value="4" id="star-4"> <label for="star-4"><i class="fas fa-star"></i></label>
      <input type="radio" name="review[rating]" value="3" id="star-3"> <label for="star-3"><i class="fas fa-star"></i></label>
      <input type="radio" name="review[rating]" value="2" id="star-2"> <label for="star-2"><i class="fas fa-star"></i></label>
      <input type="radio" name="review[rating]" value="1" id="star-1"> <label for="star-1"><i class="fas fa-star"></i></label> -->
    </div>
    <%= f.submit class: 'btn btn-primary review-btn' %>

    <% end %>

app/views/services/_info_window.html.erb
<h2><%= service.name %></h2>
<p><%= service.address %></p>

app/views/services/index.html.erb
<div class="service-text"><h2 id="banner-typed-text" style= "text-align:center;min-height: 25px;"></h2></div>

<div class="search-form-control">
 <%= form_tag services_path, method: :get do %><%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a service"%><%= submit_tag "Search", class: "btn-search btn-primary" %><% end %>
</div>

<div class="main-container d-flex justify-content-between">
  <div class= "cards-container">
        <% @services.each do |service| %>
      <div class="card-trip">
        <%= cl_image_tag service.photo.key %>
        <div class="card-trip-infos">
          <div>
            <h2><%= service.title %></h2>
            <p>find the best <%= service.title %> in town</p>
          </div>
          <div>
            <%= link_to service_path(service), class: 'text-decoration-none' do %>
            <div class="btn btn-primary">book here</div>
            <% end %>
            <h2 class="card-trip-pricing"><%= service.price %> Euros</h2>
          </div>
        </div>
      </div>
      <% end %>

</div>


<div id="map"
     style="width: 100%; height: 100vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>

<!-- <div class="row">
  <%# @services.each do |service| %>
  <div class="co-12 colsm-6 col-md-4">
    <%#= link_to service_path(service), class: 'text-decoration-none' do %>
    <div class="card-category my-4" data-aos="zoom-in" style="card-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path('facial_service.png') %>)">
      <%#= service.title %>
    </div>
    <%# end %>
  </div>
</div> -->

app/views/services/show.html.erb
<h2 class= "display-2"><%= @service.title %></h2>

<div class="container">
  <div class="card-trip-show">

<div class="img-show">
    <%= cl_image_tag @service.photo.key %>
</div>


  <div class="card-trip-infos-show">
    <h3 class= "display-3-show"> <%= @service.name %></h3>
    <p class="address-show">Address: <%= @service.address %></p>
    <p class="card-trip-pricing-show"><%= @service.price %>€</p>
  </div>
    <% if current_user.bookings.where(service: @service).present? %>
      <p class="address-show">You Have a Booking for this Service</p>
     <% else %>
      <%= link_to "BOOK NOW", new_service_booking_path(@service), class: "btn btn-primary btn-a-color show-button" %>
     <% end %>
 <ul class="horaire">
     <li class="far fa-calendar-times"></i> Monday - Friday</li>
     <li class="far fa-clock"></i> 10h / 19h</li>
</ul>


<%= link_to "Share a review!", new_service_review_path(@service), class: 'btn btn-primary btn-review'  %>
   <% if @service.reviews.any? %>
 <div class="service-reviews" style='margin: 40px;'>
  <p style='color:black'>Reviewer: <%= @service.reviews.last.user.email %></p>
  <p style='color:black'>Comment: <%= @service.reviews.last.comment %></p>
  <p style='color:black'>Rating:  <% @service.reviews.last.rating.to_i.times do  %><i class="fas fa-star" id="voted"></i> <% end %> <% (5 - @service.reviews.last.rating.to_i).times do  %><i class="fas fa-star" id="didnt-vote"></i> <% end %>
  </p>
</div>
<% end %>

 </div>



<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-sm-4 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><%= link_to 'Services', services_path %> </li>
                            <li><%= link_to 'Check your bookings', services_path %> </li>
                        </ul>
                    </div>
                    <div class="col-sm-4 col-md-3 item">
                        <h3>About us</h3>
                        <ul>
                            <li><%= link_to 'Team', team_path %></li>
                            <li><%= link_to 'Contact', contact_path %></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 item social"><a href="https://www.facebook.com/sharer/sharer.php?u=www.beauty-first.com"><i class="icon ion-social-facebook"></i></a><a href="https://twitter.com/intent/tweet?url=www.beauty-first.com&text=Beauty%20first"><i class="icon ion-social-twitter"></i></a><a href="http://www.linkedin.com/shareArticle?mini=true&url=www.beauty-first.com&title=Beauty%20first"><i class="icon ion-social-linkedin"></i></a><a href="https://msng.link/o/?beauty-first=ig"><i class="icon ion-social-instagram"></i></a>
                        <p class="copyright">BeautyFirst © 2021</p>
                    </div>
                </div>
            </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon content-center">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">


    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= link_to services_path do %>
          <div class="nav_icons"><li class="fa fa-shopping-cart"></li></div>
          <div class="hide">Basket</div>
          <% end %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <div class="nav_icons"><li class="fas fa-warehouse"></li></div>
          <div class="hide">Register</div>
        <% end %>
        <% else %>
        <%= link_to new_user_session_path do %>
          <div class="nav_icons"><li class="far fa-user"></li></div>
          <div class="hide">Log in</div>
           <%= link_to new_user_registration_path do %>
          <div class=" nav_icons"><li class="fas fa-warehouse"></li></div>
           <div class="hide">Register</div>
           <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>